# Generated by Django 5.2.7 on 2025-11-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-cart_id']},
        ),
    ]
