# Generated by Django 5.2.7 on 2025-11-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], default='DEBIT', max_length=20)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_last_4', models.CharField(help_text='Last 4 digits of card number', max_length=4)),
                ('expiry_month', models.CharField(help_text='MM format (01-12)', max_length=2)),
                ('expiry_year', models.CharField(help_text='YY format (e.g., 25 for 2025)', max_length=2)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='main.customer')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
